spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studio_medico
    username: root
    password: password
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: None
          starttls:
            enable: true
authframework:
  jwt:
    hskey: KTlgvPcXbnLoYl6b5Ma1oG294dGoZ+fyxBqJiBjQjVo=
    audience: testaudience
    token-ttl: 86400000
